name: BOOKSTORE frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths: 
      - "client/**"
      - ".github/workflows/frontend-appservice.yml"
  workflow_dispatch:

env:
    NODE_VERSION: '20.x'                # set this to the node version to use
  
permissions:
    contents: read
    id-token: write # for azure login

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json
    
    - name: Install Frontend Dependencies
      run: |
        cd client
        npm install

    - name: Build Frontend
      run: |
        cd client
        npm run build

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: 'Deploy Frontend to Azure Static Web Apps'
      uses: Azure/static-web-apps-deploy@v1
      with:
        app_location: "client"
        output_location: "client/build"
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
