name: BOOKSTORE frontend CI/CD

on:
  push:
    branches: [ "main" ]
    paths: 
      - "client/**"
      - ".github/workflows/frontend-appservice.yml"
  workflow_dispatch:

env:
    NODE_VERSION: '20.x'                # set this to the node version to use
  
permissions:
    contents: read
    id-token: write # for azure login

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment: 
      name: ProductionApp
      url: ${{steps.deploy-to-webapp.outputs.webapp-url}}
    defaults:
      run:
        working-directory: ./client
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json
    
    - name: npm install, build, and test
      run: |
        npm install
        npm run build

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          
    - name: 'Deploy to Azure WebApp'
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: book-store-frontend
        package: ./client/dist
